// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Models;

public partial class Account
{
    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string AccountId { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Username { get; set; }

    [Column("Password_hash")]
    [StringLength(255)]
    [Unicode(false)]
    public string PasswordHash { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string ImageUrl { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Phone { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string Role { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreateAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Status { get; set; }

    [InverseProperty("Staff")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}