// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Models;

[Table("CategoryExtraMapping")]
public partial class CategoryExtraMapping
{
    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string MainCategoryId { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string ExtraCategoryId { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string Status { get; set; }

    [InverseProperty("MainCategory")]
    public virtual ICollection<Category> Categories { get; set; } = new List<Category>();
}