// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Models;

public partial class ComboItem
{
    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string ComboItemId { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string ComboId { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string ProductId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Quantity { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreateAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string MasterId { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string OrderItemMode { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Status { get; set; }

    [InverseProperty("Master")]
    public virtual ICollection<ComboItem> InverseMaster { get; set; } = new List<ComboItem>();

    [ForeignKey("MasterId")]
    [InverseProperty("InverseMaster")]
    public virtual ComboItem Master { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("ComboItems")]
    public virtual Product Product { get; set; }
}