// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Models;

public partial class OrderItem
{
    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string OrderDetailId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Quantity { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Price { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string MasterId { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string ProductId { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string OrderId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderItems")]
    public virtual Order Order { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("OrderItems")]
    public virtual Product Product { get; set; }
}