// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Models;

public partial class Order
{
    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string OrderId { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? TotalAmount { get; set; }

    [Column(TypeName = "text")]
    public string Note { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string StaffId { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string PaymentMethodId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    [ForeignKey("PaymentMethodId")]
    [InverseProperty("Orders")]
    public virtual PaymentMethod PaymentMethod { get; set; }

    [ForeignKey("StaffId")]
    [InverseProperty("Orders")]
    public virtual Account Staff { get; set; }
}