// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Models;

public partial class PaymentMethod
{
    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string PaymentMethodId { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string MethodName { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string Description { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreateAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [InverseProperty("PaymentMethod")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}