// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DAL.Models;

public partial class Product
{
    [Key]
    [StringLength(10)]
    [Unicode(false)]
    public string ProductId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string ProductName { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string CategoryId { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string Description { get; set; }

    [Column("ImageURL", TypeName = "text")]
    public string ImageUrl { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Price { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ProductType { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string ParentId { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string SizeId { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreateAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("Products")]
    public virtual Category Category { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<ComboItem> ComboItems { get; set; } = new List<ComboItem>();

    [InverseProperty("Product")]
    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}